### PR TITLE
Drafting preliminary sim

### PR DESCRIPTION
**Pull request by bxrne**
RocketPy notebook from OpenRocket
- L645 sim 
- L1720 sim

### CODE REVIEW

**Comment by bxrne** [comment]
Nvm motor ordered just L645 needed.
Apogee > 3km ✅ 
Ground hit ~10m/s

**Comment by bxrne** [comment]
Dimensions need to be double checked just incase and masses too. Altitude is a little higher than expected so I think a value may be off (Could be runway altitude)

**Comment by thesaxman** [comment]
The launch rail length is inputted as 1.2 m is it not 12 m?

**Review by thesaxman — DISMISSED** [review]
All looks good 👍

**Pull request merged**
